spring.datasource.url=jdbc:mysql://localhost:3306/skill12
spring.datasource.username=root
spring.datasource.password=lohithreddy@891

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9090